"""Strategy and experiment export formats."""

from __future__ import annotations
import json
from pathlib import Path


def export_json(record, path):
    Path(path).write_text(json.dumps(record, indent=2, sort_keys=True))
    return Path(path)


def _to_yaml(value, indent: int = 0) -> str:
    """Minimal YAML serializer for simple dict/list/scalar structures."""
    prefix = '  ' * indent
    if isinstance(value, dict):
        if not value:
            return '{}'
        lines = []
        for k, v in value.items():
            v_yaml = _to_yaml(v, indent + 1)
            if isinstance(v, (dict, list)) and v:
                lines.append(f'{prefix}{k}:')
                lines.append(v_yaml)
            else:
                lines.append(f'{prefix}{k}: {v_yaml}')
        return '\n'.join(lines)
    elif isinstance(value, list):
        if not value:
            return '[]'
        return '\n'.join(f'{prefix}- {_to_yaml(item, indent)}' for item in value)
    elif isinstance(value, bool):
        return 'true' if value else 'false'
    elif isinstance(value, (int, float)):
        return str(value)
    elif value is None:
        return 'null'
    else:
        s = str(value)
        # Quote strings that contain YAML special chars
        if any(c in s for c in (':','#','[',']','{','}','&','*','!','|','>',"'",'"','%','@','`')):
            return json.dumps(s)  # Use JSON string quoting
        return s

def export_yaml(record: dict, path) -> Path:
    """Export strategy record as valid YAML."""
    content = _to_yaml(record) + '\n'
    Path(path).write_text(content, encoding='utf-8')
    return Path(path)


def export_python(record, path):
    expression = record.get("expression", "")
    Path(path).write_text(
        f"# Generated by Sizon\nEXPRESSION = {expression!r}\nSTRATEGY_ID = {record.get('strategy_id','')!r}\n"
    )
    return Path(path)


def notebook_template(path):
    payload = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["# Sizon Research Notebook"],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import sizon as sz\n",
                    "feed = sz.DataFeed.from_csv('data.csv')\n",
                ],
            },
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    Path(path).write_text(json.dumps(payload, indent=2))
    return Path(path)
