"""Strategy and experiment export formats."""

from __future__ import annotations
import json
from pathlib import Path


def export_json(record, path):
    Path(path).write_text(json.dumps(record, indent=2, sort_keys=True))
    return Path(path)


def export_yaml(record, path):
    lines = []
    for k, v in record.items():
        lines.append(f"{k}: {json.dumps(v,default=str)}")
    Path(path).write_text("\n".join(lines) + "\n")
    return Path(path)


def export_python(record, path):
    expression = record.get("expression", "")
    Path(path).write_text(
        f"# Generated by Sizon\nEXPRESSION = {expression!r}\nSTRATEGY_ID = {record.get('strategy_id','')!r}\n"
    )
    return Path(path)


def notebook_template(path):
    payload = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["# Sizon Research Notebook"],
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import sizon as sz\n",
                    "feed = sz.DataFeed.from_csv('data.csv')\n",
                ],
            },
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    Path(path).write_text(json.dumps(payload, indent=2))
    return Path(path)
